### ISSUE TITLE
Question about the unconditional expectation in GMM

### ISSUE THREAD

**Issue by Alalalalaki** [rickecon/Notebooks#1]
Hi,

I read your GMM note and it is very helpful to understand this estimator. I can go through with the examples of MLE and OLS but I find I have no idea about what is the data moment and the model moment for moment conditions that are driven from an unconditional expectation, e.g. 𝐸[𝜀 * IVs]=0. I know the moment in code can be m = e.T @ IVs @ IVs.T @ e and then I can optimize m to get the parameters. But I don't know how to do a 2-step GMM in such case. 

Thanks.

**Comment by rickecon** [comment]
@Alalalalaki Do you have a specific question for me? In the GMM notebook, I have derived a general estimator for nonlinear models. IV estimation is a special case (linear, IV moment conditions based on expectations operators).

**Comment by Alalalalaki** [comment]
@rickecon Thanks for your reply. The model I am trying now is the semi-parametric control variable approach of production function estimation (OP/LP/ACF). The image below is a simple explanation of the process if you don't mind to have a look. I wonder if it is possible to do a 2 step GMM for this model.

![image](https://user-images.githubusercontent.com/31154974/53188025-c9ef6c80-3647-11e9-8016-d27551c487bc.png)

**Comment by rickecon** [comment]
The two step intuition of IV estimation is integrated into the single criterion function approach specified in my GMM notebook. The derivation of the generalized IV approach is nicely outlined in Davidson and MacKinnon (2004, pp. 318-321), *Economic Theory and Methods*, Oxford University Press. See the entire Chapter 8 for a broader treatment.
